// these are some examples for messages
export const MESSAGES = {
  welcome: "welcome to node-js backend.",
  noError: "",
  noMessage: "",
  intrnlSrvrErr: "Please try after some time.",
  unAuthAccess: "Unauthorized access ",
  authAccess: "authorized access ",
  tokenGenError: "Error while generating access token",
  invalidEmail: "Please fill valid Email Address",
  emailCantEmpty: "Please fill Email Address",
  passCantEmpty: "Password can't be empty",
  invalidPassword: "Password invalid.",
  invalidMobile: "Please fill valid Phone No",
  emptyPhoneNumber: "Phone number is required.",
  emptyId: "Please enter id.",
  invalidId: "Please enter valid id.",
  alreadyOpen: "Status already open.",
  alreadyClose: "Status already close.",
  alreadyActive: "Status already active.",
  alreadyInActive: "Status already inactive.",
  changeSuccess: "Status updated successfully.",
  emptyStatus: "Please select status.",
  changeStatusErr: "There is some issue with status change.",
  dataNotFound: "Data not found.",
  logoutSuccessfully: "Logout Successfully.",
  userNotFound: "User not found.",
  alreadyRegisteredWithSocial: "You already registered with social media.",
  passwordMismatch: "Password mismatch",
  newAndConfPasswordNotSame: "New & Confirm Password must be same.",
  atLeastOneField: "Please enter atLeast one Field for edit.",
  emailSended: "Check your mail to reset your password.",
  otpRequired: "Otp is Required.",
  otpVerified: "Otp verified successfully.",
  resetPasswordSuccess: "Password reset successfully.",
  appLanguageChangeSuccess: "App language updated successfully.",
  newsLanguageChangeSuccess: "News language updated successfully.",
  languagesNotFound: "Languages not found.",
  invalidType: "Type invalid.",
  updatedSuccess: "Updated successfully.",
  listingSuccess: "Listing successfully.",
  deleteSuccess: "Deleted successfully.",
  issueWithList: "There is some issue with list.",
  invalidNewPassword: "New Password invalid.",
  typeRequired: "Type required.",
  articleNotFound: "Article not found.",
  readLaterArticleNotFound: "Read later article not found",
  articleIdRequired: "Article id required.",
  articleIdInvalid: "Article id Invalid.",
  bundleNotFound: "Bundle not found.",
  bundleNotAccess: "You have no permission to access this bundle",
  publicationNotFound: "Publication not found.",
  topicNotFound: "Topic not found",
  catagoryNotFound: "Category not found.",
  getByIdSuccess: "Get by id successfully.",
  issWithupdate: "There is some issue with update.",
  invalidOtp: "Invalid OTP",
  invalidToken: "Invalid access token.",
  incorrectPass: "Invalid email or passoword",
  InternalServerError: "Internal server error.",
  ok: "Ok.",
  statusTrue: true,
  statusFalse: false,
  fileNotFound: "File not found.",
  userInactive: "User is inactive.",
  issWithDashboardDetail: "There is some issue with get dashboardDetail.",
};
